{
	"name": "ExperimentABCD",
	"lsl_stream_name": "NVX136_Data",
	"inlet": "lsl",
	"raw_data_path": "",
	"hostname_port": "",
	"dc": true,
	"prefilter_band_lower_bound": 3.0,
	"prefilter_band_upper_bound": 4.0,
	"plot_raw": true,
	"plot_signals": true,
	"show_subject_window": true,
	"discard_channels": "",
	"reference_sub": "",
	"show_proto_rectangle": true,
	"show_notch_filters": true,
	"signal_scheme": {
		"nodes": [
			{
				"title": "LSL Input",
				"description": "No description",
				"inputs": [],
				"outputs": [
					{
						"text": "LSL data stream",
						"data_type": {
							"data_id": 1,
							"title": "Unknown data",
							"__class__": {
								"__module__": "nfb_studio.widgets.scheme.node.connection.data_type",
								"__qualname__": "DataType"
							}
						},
						"__class__": {
							"__module__": "nfb_studio.widgets.scheme.node.connection.output",
							"__qualname__": "Output"
						}
					}
				],
				"messages": [],
				"position": {
					"x": 4.000416666666667,
					"y": 3.661875,
					"__class__": {
						"__module__": "PySide2.QtCore",
						"__qualname__": "QPointF"
					}
				},
				"data_source": "NVX136_Data",
				"__class__": {
					"__module__": "nfb_studio.widgets.signal_nodes.lsl_input",
					"__qualname__": "LSLInput"
				}
			},
			{
				"title": "LSL Input",
				"description": "No description",
				"inputs": [],
				"outputs": [
					{
						"text": "LSL data stream",
						"data_type": {
							"data_id": 1,
							"title": "Unknown data",
							"__class__": {
								"__module__": "nfb_studio.widgets.scheme.node.connection.data_type",
								"__qualname__": "DataType"
							}
						},
						"__class__": {
							"__module__": "nfb_studio.widgets.scheme.node.connection.output",
							"__qualname__": "Output"
						}
					}
				],
				"messages": [],
				"position": {
					"x": -1.1558333333333333,
					"y": -0.8797916666666667,
					"__class__": {
						"__module__": "PySide2.QtCore",
						"__qualname__": "QPointF"
					}
				},
				"data_source": "NVX136_Data",
				"__class__": {
					"__module__": "nfb_studio.widgets.signal_nodes.lsl_input",
					"__qualname__": "LSLInput"
				}
			},
			{
				"title": "Derived Signal Export",
				"description": "No description",
				"inputs": [
					{
						"text": "Input",
						"data_type": {
							"data_id": 1,
							"title": "Unknown data",
							"__class__": {
								"__module__": "nfb_studio.widgets.scheme.node.connection.data_type",
								"__qualname__": "DataType"
							}
						},
						"__class__": {
							"__module__": "nfb_studio.widgets.scheme.node.connection.input",
							"__qualname__": "Input"
						}
					}
				],
				"outputs": [
					{
						"text": "Output",
						"data_type": {
							"data_id": 1,
							"title": "Unknown data",
							"__class__": {
								"__module__": "nfb_studio.widgets.scheme.node.connection.data_type",
								"__qualname__": "DataType"
							}
						},
						"__class__": {
							"__module__": "nfb_studio.widgets.scheme.node.connection.output",
							"__qualname__": "Output"
						}
					}
				],
				"messages": [],
				"position": {
					"x": 4.781666666666667,
					"y": 1.3285416666666665,
					"__class__": {
						"__module__": "PySide2.QtCore",
						"__qualname__": "QPointF"
					}
				},
				"signal_name": "Signal123",
				"__class__": {
					"__module__": "nfb_studio.widgets.signal_nodes.derived_signal_export",
					"__qualname__": "DerivedSignalExport"
				}
			},
			{
				"title": "Standardise",
				"description": "No description",
				"inputs": [
					{
						"text": "Input",
						"data_type": {
							"data_id": 1,
							"title": "Unknown data",
							"__class__": {
								"__module__": "nfb_studio.widgets.scheme.node.connection.data_type",
								"__qualname__": "DataType"
							}
						},
						"__class__": {
							"__module__": "nfb_studio.widgets.scheme.node.connection.input",
							"__qualname__": "Input"
						}
					}
				],
				"outputs": [
					{
						"text": "Output",
						"data_type": {
							"data_id": 1,
							"title": "Unknown data",
							"__class__": {
								"__module__": "nfb_studio.widgets.scheme.node.connection.data_type",
								"__qualname__": "DataType"
							}
						},
						"__class__": {
							"__module__": "nfb_studio.widgets.scheme.node.connection.output",
							"__qualname__": "Output"
						}
					}
				],
				"messages": [],
				"position": {
					"x": 0.8233333333333334,
					"y": 2.5056249999999998,
					"__class__": {
						"__module__": "PySide2.QtCore",
						"__qualname__": "QPointF"
					}
				},
				"average": 0,
				"standard_deviation": 1,
				"__class__": {
					"__module__": "nfb_studio.widgets.signal_nodes.standardise",
					"__qualname__": "Standardise"
				}
			},
			{
				"title": "Envelope Detector",
				"description": "No description",
				"inputs": [
					{
						"text": "Input",
						"data_type": {
							"data_id": 1,
							"title": "Unknown data",
							"__class__": {
								"__module__": "nfb_studio.widgets.scheme.node.connection.data_type",
								"__qualname__": "DataType"
							}
						},
						"__class__": {
							"__module__": "nfb_studio.widgets.scheme.node.connection.input",
							"__qualname__": "Input"
						}
					}
				],
				"outputs": [
					{
						"text": "Output",
						"data_type": {
							"data_id": 1,
							"title": "Unknown data",
							"__class__": {
								"__module__": "nfb_studio.widgets.scheme.node.connection.data_type",
								"__qualname__": "DataType"
							}
						},
						"__class__": {
							"__module__": "nfb_studio.widgets.scheme.node.connection.output",
							"__qualname__": "Output"
						}
					}
				],
				"messages": [],
				"position": {
					"x": 1.5108333333333335,
					"y": -0.09854166666666668,
					"__class__": {
						"__module__": "PySide2.QtCore",
						"__qualname__": "QPointF"
					}
				},
				"smoothing_factor": 0,
				"method": "Rectification",
				"__class__": {
					"__module__": "nfb_studio.widgets.signal_nodes.envelope_detector",
					"__qualname__": "EnvelopeDetector"
				}
			}
		],
		"edges": [
			{
				"source": {
					"node_index": 1,
					"connection_index": 0
				},
				"target": {
					"node_index": 4,
					"connection_index": 0
				}
			},
			{
				"source": {
					"node_index": 4,
					"connection_index": 0
				},
				"target": {
					"node_index": 2,
					"connection_index": 0
				}
			}
		],
		"__class__": {
			"__module__": "nfb_studio.widgets.scheme.scheme",
			"__qualname__": "Scheme"
		}
	},
	"sequence_scheme": {
		"nodes": [
			{
				"title": "Block1",
				"description": "No description",
				"inputs": [
					{
						"text": "Input",
						"data_type": {
							"data_id": 1,
							"title": "Unknown data",
							"__class__": {
								"__module__": "nfb_studio.widgets.scheme.node.connection.data_type",
								"__qualname__": "DataType"
							}
						},
						"__class__": {
							"__module__": "nfb_studio.widgets.scheme.node.connection.input",
							"__qualname__": "Input"
						}
					}
				],
				"outputs": [
					{
						"text": "Output",
						"data_type": {
							"data_id": 1,
							"title": "Unknown data",
							"__class__": {
								"__module__": "nfb_studio.widgets.scheme.node.connection.data_type",
								"__qualname__": "DataType"
							}
						},
						"__class__": {
							"__module__": "nfb_studio.widgets.scheme.node.connection.output",
							"__qualname__": "Output"
						}
					}
				],
				"messages": [],
				"position": {
					"x": -0.46833333333333327,
					"y": -0.8277083333333334,
					"__class__": {
						"__module__": "PySide2.QtCore",
						"__qualname__": "QPointF"
					}
				},
				"__class__": {
					"__module__": "nfb_studio.widgets.sequence_nodes.block_node",
					"__qualname__": "BlockNode"
				}
			},
			{
				"title": "Block2",
				"description": "No description",
				"inputs": [
					{
						"text": "Input",
						"data_type": {
							"data_id": 1,
							"title": "Unknown data",
							"__class__": {
								"__module__": "nfb_studio.widgets.scheme.node.connection.data_type",
								"__qualname__": "DataType"
							}
						},
						"__class__": {
							"__module__": "nfb_studio.widgets.scheme.node.connection.input",
							"__qualname__": "Input"
						}
					}
				],
				"outputs": [
					{
						"text": "Output",
						"data_type": {
							"data_id": 1,
							"title": "Unknown data",
							"__class__": {
								"__module__": "nfb_studio.widgets.scheme.node.connection.data_type",
								"__qualname__": "DataType"
							}
						},
						"__class__": {
							"__module__": "nfb_studio.widgets.scheme.node.connection.output",
							"__qualname__": "Output"
						}
					}
				],
				"messages": [],
				"position": {
					"x": 0.042083333333333396,
					"y": 1.3389583333333333,
					"__class__": {
						"__module__": "PySide2.QtCore",
						"__qualname__": "QPointF"
					}
				},
				"__class__": {
					"__module__": "nfb_studio.widgets.sequence_nodes.block_node",
					"__qualname__": "BlockNode"
				}
			},
			{
				"title": "Group2",
				"description": "No description",
				"inputs": [
					{
						"text": "Input",
						"data_type": {
							"data_id": 1,
							"title": "Unknown data",
							"__class__": {
								"__module__": "nfb_studio.widgets.scheme.node.connection.data_type",
								"__qualname__": "DataType"
							}
						},
						"__class__": {
							"__module__": "nfb_studio.widgets.scheme.node.connection.input",
							"__qualname__": "Input"
						}
					}
				],
				"outputs": [
					{
						"text": "Output",
						"data_type": {
							"data_id": 1,
							"title": "Unknown data",
							"__class__": {
								"__module__": "nfb_studio.widgets.scheme.node.connection.data_type",
								"__qualname__": "DataType"
							}
						},
						"__class__": {
							"__module__": "nfb_studio.widgets.scheme.node.connection.output",
							"__qualname__": "Output"
						}
					}
				],
				"messages": [],
				"position": {
					"x": 2.9483333333333337,
					"y": 2.880625,
					"__class__": {
						"__module__": "PySide2.QtCore",
						"__qualname__": "QPointF"
					}
				},
				"__class__": {
					"__module__": "nfb_studio.widgets.sequence_nodes.group_node",
					"__qualname__": "GroupNode"
				}
			}
		],
		"edges": [
			{
				"source": {
					"node_index": 1,
					"connection_index": 0
				},
				"target": {
					"node_index": 2,
					"connection_index": 0
				}
			}
		],
		"__class__": {
			"__module__": "nfb_studio.widgets.scheme.scheme",
			"__qualname__": "Scheme"
		}
	},
	"blocks": {
		"data": {
			"Block1": {
				"duration": 10.0,
				"feedback_source": "All",
				"feedback_type": "Baseline",
				"random_bound": "SimCircle",
				"video_path": "",
				"mock_signal_path": "",
				"mock_signal_dataset": "",
				"mock_previous": 0,
				"mock_previous_reverse": false,
				"mock_previous_random": false,
				"start_data_driven_filter_designer": false,
				"pause": false,
				"beep": false,
				"update_statistics": false,
				"__class__": {
					"__module__": "nfb_studio.block.block",
					"__qualname__": "Block"
				}
			},
			"Block2": {
				"duration": 10.0,
				"feedback_source": "All",
				"feedback_type": "Baseline",
				"random_bound": "SimCircle",
				"video_path": "",
				"mock_signal_path": "",
				"mock_signal_dataset": "",
				"mock_previous": 0,
				"mock_previous_reverse": false,
				"mock_previous_random": false,
				"start_data_driven_filter_designer": true,
				"pause": true,
				"beep": true,
				"update_statistics": true,
				"__class__": {
					"__module__": "nfb_studio.block.block",
					"__qualname__": "Block"
				}
			}
		},
		"__class__": {
			"__module__": "nfb_studio.block.block_dict",
			"__qualname__": "BlockDict"
		}
	},
	"groups": {
		"data": {
			"Group1": {
				"blocks": [],
				"repeats": [],
				"__class__": {
					"__module__": "nfb_studio.group.group",
					"__qualname__": "Group"
				}
			},
			"Group2": {
				"blocks": [
					"Block1",
					"Block2"
				],
				"repeats": [
					1,
					2
				],
				"__class__": {
					"__module__": "nfb_studio.group.group",
					"__qualname__": "Group"
				}
			}
		},
		"__class__": {
			"__module__": "nfb_studio.group.group_dict",
			"__qualname__": "GroupDict"
		}
	},
	"__class__": {
		"__module__": "nfb_studio.experiment.experiment",
		"__qualname__": "Experiment"
	}
}